<div class="festi-cart-baner">
    <a class="festi-cart-go-woocart button-primary" href="http://codecanyon.net/item/woocommerce-cart-woocart-pro/7992078?ref=Festi-Team">
        <?php _e('GET WOOCART PRO NOW!', $this->_languageDomain); ?>
    </a>
    <h1>
        <?php _e('WooCart Popup Lite', $this->_languageDomain); ?>
    </h1>
    <p>
       <?php _e('Why go pro? Ability to do dropdown ajax cart in fixed position, in menu, sidebars, customize any settings without CSS and coding and many more', $this->_languageDomain); ?>
    </p>
</div>